// <auto-generated />
using System;
using InvoiceEngine.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceEngine.API.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615210821_RemoveArticles")]
    partial class RemoveArticles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Clients_IdentificationNumber")
                        .HasFilter("[IdentificationNumber] IS NOT NULL");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InsuranceCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InsuranceCompanies", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("ExpiresAt")
                        .HasColumnType("DATE");

                    b.Property<string>("IncotermCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(3)");

                    b.Property<DateOnly>("IssuedAt")
                        .HasColumnType("DATE");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TransactionEndDate")
                        .HasColumnType("DATE");

                    b.Property<DateOnly>("TransactionStartDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_IssueExpireRange", "[ExpiresAt] > [IssuedAt]");

                            t.HasCheckConstraint("CK_Invoice_TransactionDateRange", "[TransactionEndDate] > [TransactionStartDate]");
                        });
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceClient", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectCode")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId", "ClientId", "SubjectCode");

                    b.HasIndex("ClientId");

                    b.ToTable("InvoiceClients");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceCustomIncotermObligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FromSubjectCode")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeCode")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentageAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("ToSubjectCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "FromSubjectCode", "ToSubjectCode", "ItemTypeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomIncotermObligations_Invoice_SubjectFrom_SubjectTo_ItemType");

                    b.ToTable("CustomIncotermObligations", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomIncotermObligations_PercentageAmount", "PercentageAmount >= 0 AND PercentageAmount <= 100");
                        });
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemInsuranceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ExpiresAt")
                        .HasColumnType("date");

                    b.Property<int>("InsuranceCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId");

                    b.ToTable("InvoiceItemInsuranceDetails", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemObligation", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("int");

                    b.Property<int>("FromClientSubjectCode")
                        .HasColumnType("int");

                    b.Property<int>("ToClientSubjectCode")
                        .HasColumnType("int");

                    b.Property<decimal>("OwingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemId", "FromClientSubjectCode", "ToClientSubjectCode");

                    b.ToTable("InvoiceItemObligations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Obligation_DifferentClients", "[FromClientSubjectCode] <> [ToClientSubjectCode]");
                        });
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId");

                    b.ToTable("InvoiceItemOrderDetails", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemTransportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AddressTo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("int");

                    b.Property<int?>("TransportCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId");

                    b.ToTable("InvoiceItemTransportDetails", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_InvoiceItemTypes_Name");

                    b.ToTable("InvoiceItemTypes", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("SellDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 2)")
                        .HasComputedColumnSql("[Quantity] * [Price]", true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UnitOfMeasureCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.TransportCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_TransportCompanies_IdentificationNumber")
                        .HasFilter("IdentificationNumber IS NOT NULL");

                    b.ToTable("TransportCompanies", (string)null);
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceClient", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.Client", "Client")
                        .WithMany("InvoiceClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceClients_ClientId");

                    b.HasOne("InvoiceEngine.API.Database.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceClients")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceClients_InvoiceId");

                    b.Navigation("Client");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceCustomIncotermObligation", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.Invoice", "Invoice")
                        .WithMany("CustomIncotermObligations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceCustomIncotermObligations_InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemInsuranceDetail", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.InvoiceItem", null)
                        .WithMany("ItemInsuranceDetails")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemObligation", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.InvoiceItem", "InvoiceItem")
                        .WithMany("ItemObligations")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItemObligations_InvoiceItemId");

                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemOrderDetail", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.InvoiceItem", null)
                        .WithMany("ItemOrderDetails")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItemTransportDetail", b =>
                {
                    b.HasOne("InvoiceEngine.API.Database.Entities.InvoiceItem", null)
                        .WithMany("ItemTransportDetails")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.Client", b =>
                {
                    b.Navigation("InvoiceClients");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.Invoice", b =>
                {
                    b.Navigation("CustomIncotermObligations");

                    b.Navigation("InvoiceClients");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("InvoiceEngine.API.Database.Entities.InvoiceItem", b =>
                {
                    b.Navigation("ItemInsuranceDetails");

                    b.Navigation("ItemObligations");

                    b.Navigation("ItemOrderDetails");

                    b.Navigation("ItemTransportDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
