name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj','**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies (working dir)
        working-directory: InvoiceEngine.API
        run: dotnet restore

      - name: Build solution
        working-directory: InvoiceEngine.API
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test InvoiceEngine.API.UnitTests/InvoiceEngine.API.UnitTests.csproj --configuration Release --no-build

      - name: Run integration tests
        run: dotnet test InvoiceEngine.API.IntegrationTests/InvoiceEngine.API.IntegrationTests.csproj --configuration Release --no-build


      - name: Publish API (optional)
        if: github.ref == 'refs/heads/main'
        working-directory: InvoiceEngine.API
        run: dotnet publish src/InvoiceEngine.API/InvoiceEngine.API.csproj -c Release -o ./publish
